### ISSUE TITLE
Exported Chart Clipped When Not SVG Type

### ISSUE THREAD

**Issue by wergeld** [highcharts/node-export-server#134]
#### Expected behaviour
Exporting chart to JPG, PNG, and PDF should have same format as with SVG when using nodejs export server we maintain. 

#### Actual behaviour
When using our export server the left side of the chart is clipped such that our xAxis labels are missing the left text. When we export the same chart with the same code to export.highcharts.com there is no clipping of text
Actual behavior with PDF/PNG/JPG (using JPG as example) using our 2.0.10 node export server:
![image](https://user-images.githubusercontent.com/133511/38877992-ec15bcba-422d-11e8-967f-1c9cb3327c4e.png)

Same chart using export.highcharts.com:
![image](https://user-images.githubusercontent.com/133511/38878065-1ebb50c6-422e-11e8-95fd-314e3d59ea3d.png)

This does not affect SVG exports.

#### Reproduction steps
Code used is export server 2.0.10 running on Windows with nodejs v8x.
Our highstock code is 5.0.10.
You can see an example on this [jsFiddle](http://jsfiddle.net/wergeld/pw09m98v/).
Change the exporting.url to see our server's output.

**Comment by cvasseng** [comment]
Hi, the server at `export.highcharts.com` runs the master branch with no modifications. The only difference I can see based on your log outputs is that you're on windows while we're running it on linux. 

I've fixed the issue causing the CDN pull to fail when using a Highcharts version older than 6, it has been pushed to master. So you should be able to use the latest now if you include the dependency using the github link - could you please give that a shot and see if it resolves your issue?

**Comment by wergeld** [comment]
Used github repo to install export server 2.0.14. Able to use highcharts 5.0.10 for installing now.
However, clipped export still occurs on all but SVG. Here is output from export log:

> Mon May 07 2018 07:31:36 GMT-0400 (Eastern Daylight Time) [verbose] phantom 1 - spawning worker
> Mon May 07 2018 07:31:36 GMT-0400 (Eastern Daylight Time) [verbose] attaching exit listeners to the process..
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [verbose] phantom 2 - spawning worker
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [verbose] phantom 3 - spawning worker
> Mon May 07 2018 07:31:36 GMT-0400 (Eastern Daylight Time) [verbose] Pool started: 
>     maxWorkers: 4 
>     initialWorkers: 4 
>     workLimit: 60 
>     listening to process exit: true
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [verbose] phantom 4 - spawning worker
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [notice] https server started on port 443
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [error] phantom worker 4 error - SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
> 
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [error] phantom worker 2 error - SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
> 
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [error] phantom worker 1 error - SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
> 
> Mon May 07 2018 07:31:42 GMT-0400 (Eastern Daylight Time) [error] phantom worker 3 error - SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"
> 
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [verbose] got incoming HTTP request 0f145df11ad24918aa2ccb2689bb7d78
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [verbose] starting export
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [verbose] parsing input as svg
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [verbose] phantom - found available worker
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [verbose] phantom - received work, finding available worker
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [verbose] phantom 1 - starting work
> Mon May 07 2018 07:33:52 GMT-0400 (Eastern Daylight Time) [notice] phantom worker 1 finished work 0f145df11ad24918aa2ccb2689bb7d78 in 23 ms
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [verbose] got incoming HTTP request a718807525cb438a84a067b618b8d0a1
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [verbose] parsing input as svg
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [verbose] phantom - received work, finding available worker
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [verbose] phantom 2 - starting work
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [verbose] phantom - found available worker
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [verbose] starting export
> Mon May 07 2018 07:34:02 GMT-0400 (Eastern Daylight Time) [notice] phantom worker 2 finished work a718807525cb438a84a067b618b8d0a1 in 122 ms

The first export is the SVG and the second is the JPG. The JPG/PNG/PDF images are still clipped on the left.

**Comment by cvasseng** [comment]
Do you have a phantomjs installation that you've manually installed, or do you depend on NPM installing the correct one?

I'm unable to reproduce the clipping on my local setup (macOS), so I'm wondering if there are some configuration differences with phantom itself.

**Comment by wergeld** [comment]
This is the phantomJS installed by the npm install. It is listed as:

> phantomjs-prebuilt@2.1.14

I have done no custom configuration other than to create a startup script to point to our SSL certs (and for this issue the logging):
`C:\Users\taskscheduler\AppData\Roaming\npm\highcharts-export-server --enableServer 1 --sslPath C:\highchartsExport --sslOnly true --tmpdir C:\highchartsExport\tmp --logDest C:\highchartsExport\logs --logLevel 4`

**Comment by wergeld** [comment]
Update:
Installed the Windows Fonts (from [here](https://unix.stackexchange.com/questions/217365/how-to-install-microsoft-true-type-fonts-for-centos-7)) and the CentOS server exports now match (no clipping).

However, this does not resolve our environment issue. We are constrained to Windows - and it already has the Windows fonts on it (we are not using any special fonts in our charts - whatever the highcharts system uses).

**Comment by cvasseng** [comment]
Could you try to explicitly set the font family to e.g. Arial (`chart.style.fontFamily`)?

If it still doesn't work, it will give an indication that it's likely not directly related to font metrics.

**Comment by wergeld** [comment]
I set to use Verdana and Arial from the chart create scripts. Now requests do not clip. However, this was not needed under the Java export server which also ran under Windows and did not have the Lucinda Grande. Lucida Sans Unicode, Helvetica, or sans-serif fonts and there was no issue with exporting.

**Comment by cvasseng** [comment]
The difference may be due to different PhantomJS versions between the node server and the old Java server. I would expect this to work (and it does on our systems), so it seems like there may an issue with font fallbacks and metrics when falling back specifically in Phantom on the version of Windows you're on. 

I honestly don't know that we can do much about this, apart from recommending you either install the missing fonts, or only use fonts available by default on Windows, but I will see if we can reproduce it on a windows box/vm internally somehow. Which version are you using?

**Comment by wergeld** [comment]
We are using Windows Server 2016 and our existing export server using Java app is running Windows Server 2012 (which does not have this font issue).

**Comment by PaulDalek** [comment]
Closing issue due to inactivity.
