### ISSUE TITLE
Highcharts export server failing to start up due to "TypeError: invalid options argument"

### ISSUE THREAD

**Issue by daddyg** [highcharts/node-export-server#233]
#### Expected behaviour
Running highcharts-export-server should start the server.

#### Actual behaviour
The server attempts to start up but throws the following error

```
TypeError: invalid options argument
    at optsArg (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/highcharts-export-server/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/highcharts-export-server/node_modules/mkdirp/index.js:11:10)
    at log (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/highcharts-export-server/lib/logger.js:151:17)
    at attachExitListeners (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/highcharts-export-server/lib/phantompool.js:55:5)
    at Object.init [as initPool] (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/highcharts-export-server/lib/phantompool.js:314:9)
    at Object.<anonymous> (/opt/elasticbeanstalk/node-install/node-v10.17.0-linux-x64/lib/node_modules/highcharts-export-server/bin/cli.js:193:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

#### Reproduction steps
- Install NodeJS 10.15.3 or 10.17.0
- Install NPM 6.9.0
- Install highcharts-export-server with npm install highcharts-export-server -g
 - Specify Highcharts Version 6.0.2
- Run with highcharts-export-server --enableServer 1 --port 8081 --logDest ./ --logLevel 4

####Suggested reason for issue
A new version of mkdirp was released 14 days ago on the 24/01/2020. This update will be automatically pulled in as the version number is not pinned in package.json

This update included a fairly hefty rewrite, and it looks like it is no longer possible to call mkdirp with a function as the second argument. This is leading to the error, when the logging is being set up.

**Comment by javierdompablo** [comment]
Please any solution for these problem?

**Comment by daddyg** [comment]
I don't know if the solution has been implemented yet, but a workaround that worked for me was to remove the logDest parameter. Obviously this means logs are no longer written to disk, but that was good enough for me

**Comment by jonnytest1** [comment]
mkdirp has swiched to promised instead of callbacks

**Comment by PaulDalek** [comment]
This has been resolved by the e74873950290e286a08ddd60f550ecff544b2638.

**Comment by pierregangloff** [comment]
I still see this issue in the latest version "2.0.29" where package.json has "mkdirp": "^1.0.4".

The only way to make it work is to remove the "-tmpdir ~/highchartsExportServer/tmp -logDest ~/highchartsExportServer/logs" arguments.

client call: 
curl -X POST -d "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"xAxis\": {\"categories\": [\"Jan\", \"Feb\", \"Mar\"]}, \"series\": [{\"data\": [29.9, 71.5, 106.4]}]}}" http://54.221.118.52:7801 -o feb10-1644.png

command line script that results in error:
 ./bin/cli.js -enableServer 1 -tmpdir ~/highchartsExportServer/tmp -logDest ~/highchartsExportServer/logs

command line that results in success:
./bin/cli.js -enableServer 1

ERROR that comes up with the first command line (with -logDest):
./bin/cli.js -enableServer 1 -tmpdir ~/highchartsExportServer/tmp -logDest ~/highchartsExportServer/logs
    __  ___       __         __               __                      
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______                
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/                
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )                 
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/                  
        ____//___/                  __     _____                          
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /    
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/     
              /_/                                                         
               
                                                                  v2.0.29
TypeError: invalid options argument
    at optsArg (/home/ec2-user/git/node-export-server/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/home/ec2-user/git/node-export-server/node_modules/mkdirp/index.js:11:10)
    at log (/home/ec2-user/git/node-export-server/lib/logger.js:151:17)
    at handlePost (/home/ec2-user/git/node-export-server/lib/server.js:180:9)
    at Layer.handle [as handle_request] (/home/ec2-user/git/node-export-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ec2-user/git/node-export-server/node_modules/express/lib/router/route.js:137:13)
    at limiter (/home/ec2-user/git/node-export-server/lib/server.js:62:9)
    at Layer.handle [as handle_request] (/home/ec2-user/git/node-export-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ec2-user/git/node-export-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ec2-user/git/node-export-server/node_modules/express/lib/router/route.js:112:3)
^C

Message that comes up when I skip the logDest:
./bin/cli.js -enableServer 1
    __  ___       __         __               __                      
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______                
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/                
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )                 
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/                  
        ____//___/                  __     _____                          
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /    
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/     
              /_/                                                         
               
                                                                  v2.0.29
Wed Feb 10 2021 21:52:41 GMT+0000 (Coordinated Universal Time) [warning] request 3f992636c8fa40fd925c10447974bfdf from ::ffff:66.130.2.188 was empty: {
  "{\"infile\":{\"title\": {\"text\": \"Steep Chart\"}, \"xAxis\": {\"categories\": ": {
    "\"Jan\", \"Feb\", \"Mar\"": {
      "29.9, 71.5, 106.4": ""
    }
  }
} headers: {
  "host": "54.221.118.52:7801",
  "user-agent": "curl/7.55.1",
  "accept": "*/*",
  "content-length": "136",
  "content-type": "application/x-www-form-urlencoded"
}
^C


Could it be the same mkdirp issue with the dreaded carret ^ dependency in package.json ?!?! Thanks!

**Comment by pierregangloff** [comment]
Sure enough, someone changed package.json 8 days ago to update the mkdirp version. If I manually change mkdirp back to 0.5.0 ("mkdirp": "0.5.0") in package.json, and the logDest option starts working again. So, it seems like someone blindly updated versions, which broke the logDest...

**Comment by pierregangloff** [comment]
Thanks @cvasseng , your fix from last night fixed it :) Great job on this project!! I'm having fun deploying the highcharts export server to a daemonized PM2 cluster (instead of "forever") on an Amazon EC2 machine, behind an Automatic Scaling Group, behind an Elastic Load balancer on AWS. We had initially done it by calling highcharts through a lambda function on AWS but there was the issue of "initial phantomjs load time" so we're now starting highcharts ahead of time (and leaving it running on the EC2 machines) so that highcharts is always "warm" and ready to process requests = there is no delay in creating a new chart (no initial load time/delay) so this should all work great! Thanks again to the whole highcharts team for this great project!
