### ISSUE TITLE
MomentJS + Highcharts: `time.timezone` option does not work (`m.tz is not a function`)

### ISSUE THREAD

**Issue by jakubSzuminski** [highcharts/node-export-server#442]
#### Expected behaviour
The `time.timezone` Highcharts option should work as expected. The moment.js script is supposedly imported as it's in the default config (at least in the documentation): https://github.com/highcharts/node-export-server/tree/stable#loading-default-json-config

#### Reproduction steps
Use the following config:
```
{
  "chart": {
    "type": "line"
  },
  "series": [{
    "name": "test",
    "data": [{
      "y": 45.83,
      "x": 1692590400000
    }, {
      "y": 45.83,
      "x": 1692594000000
    }, {
      "y": 45.83,
      "x": 1692597600000
    }]
  }],
  "xAxis": {
    "type": "datetime"
  },
  "time": {
    "timezone": "America/Chicago"
  },
}
```
with `node ./bin/cli.js --infile config.json` to see the following error: `Error encountered during export: m.tz is not a function`.

**Comment by jakubSzuminski** [comment]
Fixed via https://github.com/highcharts/node-export-server/pull/444.

Closing as this will be a part of the next release.

**Comment by dancojocar** [comment]
Just performed a checkout of the stable branch that includes this fix, but I'm still encountering the initial error. Upon inspecting the configuration, I noticed that both moment-timezone.js and moment.js scripts are included. However, during page evaluation, the error persists:
```
TypeError: m.tz is not a function
    at evaluate (evaluate at setAsConfig (file:///opt/dechpc/thirdparty/node-export-server/lib/export.js:100:14), <anonymous>:0:28)
    at ExecutionContext.#evaluate (file:///opt/dechpc/thirdparty/node-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:226:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (file:///opt/dechpc/thirdparty/node-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/ExecutionContext.js:123:16)
    at async IsolatedWorld.evaluate (file:///opt/dechpc/thirdparty/node-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:126:16)
    at async CdpFrame.evaluate (file:///opt/dechpc/thirdparty/node-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/api/Frame.js:367:20)
    at async CdpPage.evaluate (file:///opt/dechpc/thirdparty/node-export-server/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:868:20)
    at async setAsConfig (file:///opt/dechpc/thirdparty/node-export-server/lib/export.js:100:3)
    at async default (file:///opt/dechpc/thirdparty/node-export-server/lib/export.js:223:9)
    at async postWork (file:///opt/dechpc/thirdparty/node-export-server/lib/pool.js:334:20)
```

**Comment by dancojocar** [comment]
That was the issue, it's working now. Thanks!
