### ISSUE TITLE
Requested error when running server on Windows

### ISSUE THREAD

**Issue by ypconstante** [highcharts/node-export-server#73]
I am trying to run the HTTP server but both Master and NPM versions are resulting in error. 

Master
```
Fri Aug 04 2017 19:03:55 GMT-0300 (Hora oficial do Brasil) [verbose] attaching exit listeners to the process..
Fri Aug 04 2017 19:03:55 GMT-0300 (Hora oficial do Brasil) [verbose] Pool started: 
    maxWorkers: 1 
    initialWorkers: 1 
    workLimit: 60 
    listening to process exit: true
Fri Aug 04 2017 19:03:55 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - spawning worker
Fri Aug 04 2017 19:03:55 GMT-0300 (Hora oficial do Brasil) [notice] http server started on port 7801
Fri Aug 04 2017 19:04:03 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request a7d5c952cf75454db520e27236b45852
Fri Aug 04 2017 19:04:03 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Fri Aug 04 2017 19:04:03 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Fri Aug 04 2017 19:04:03 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Fri Aug 04 2017 19:04:03 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Fri Aug 04 2017 19:04:03 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - starting work
Fri Aug 04 2017 19:06:03 GMT-0300 (Hora oficial do Brasil) [error] socket error: { Error: Parse Error
    at Error (native)
    at Socket.socketOnEnd (_http_server.js:425:22)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) bytesParsed: 0, code: 'HPE_INVALID_EOF_STATE' }
Error: request aborted
    at IncomingMessage.onAborted (C:\Users\yuric.PARIPASSU\Programas\highcharts-node-export-server\node-export-server\node_modules\raw-body\index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:283:11)
    at Socket.serverSocketCloseListener (_http_server.js:296:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
```

Version 1.0.21 
```
Fri Aug 04 2017 19:15:26 GMT-0300 (Hora oficial do Brasil) [verbose] attaching exit listeners to the process..
Fri Aug 04 2017 19:15:26 GMT-0300 (Hora oficial do Brasil) [verbose] Pool started: 
    maxWorkers: 1 
    initialWorkers: 1 
    workLimit: 60 
    listening to process exit: true
Fri Aug 04 2017 19:15:26 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - spawning worker
Fri Aug 04 2017 19:15:26 GMT-0300 (Hora oficial do Brasil) [notice] http server started on port 7801
Fri Aug 04 2017 19:15:28 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:31 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:33 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:36 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:38 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:39 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request d77bf12dfb2d423787e2ae846e979f22
Fri Aug 04 2017 19:15:39 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Fri Aug 04 2017 19:15:39 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Fri Aug 04 2017 19:15:39 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Fri Aug 04 2017 19:15:39 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Fri Aug 04 2017 19:15:39 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - starting work
Fri Aug 04 2017 19:15:41 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:43 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
Fri Aug 04 2017 19:15:43 GMT-0300 (Hora oficial do Brasil) [error] error doing chart: server too busy, please try again later
Fri Aug 04 2017 19:15:43 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker
Fri Aug 04 2017 19:15:43 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 2 - spawning worker
Fri Aug 04 2017 19:15:43 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 1 - process was closed
Fri Aug 04 2017 19:15:46 GMT-0300 (Hora oficial do Brasil) [verbose] reaper checking for timed out phantom processes
```

**Comment by cvasseng** [comment]
Hi, this should be fixed now (version 2.0.0). Please let me know if upgrading fixes the issue for you.

**Comment by ypconstante** [comment]
Still not working. I testes a little more and it seems to only happen when generating svg in Windows. 
I´m using the basic line example (https://www.highcharts.com/demo/line-basic) as input, and when generating png and jpg the output is generated.
When using the http://export.highcharts.com/ with svg it also works.
This time no log is being generated, I´m just getting a `Error: Server returned nothing (no headers, no data)`. The log bellow is what is shown when redoing the request after 6 minutes.

```
Mon Aug 07 2017 11:16:13 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - spawning worker
Mon Aug 07 2017 11:16:13 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 2 - spawning worker
Mon Aug 07 2017 11:16:13 GMT-0300 (Hora oficial do Brasil) [notice] http server started on port 7801
Mon Aug 07 2017 11:16:16 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 291cd45e91664428910b614c2c9d7ddc
Mon Aug 07 2017 11:16:16 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Mon Aug 07 2017 11:16:16 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Mon Aug 07 2017 11:16:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Mon Aug 07 2017 11:16:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Mon Aug 07 2017 11:16:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 2 - starting work
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request f4e5332f63834361a20458ed3f6a8745
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 3 - spawning worker
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - starting work
Mon Aug 07 2017 11:22:12 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 2 - process was closed
```

**Comment by cvasseng** [comment]
It looks like your client connection times out. How are you POSTing to the server?

**Comment by ypconstante** [comment]
I've tried with a Java Http Client (fluent-hc), Insomnia and Postman. 
The request that I´m making is just a POST to http://127.0.0.1:7801, and in the form the param type 'svg' and options with the content the basic line example.

Something interesting is that the exception in the end of Export Server output only happens on the Java call. 

Insomnia output:
```
* Preparing request to http://127.0.0.1:7801/
* Enable automatic URL encoding
* Enable SSL validation
* Replaced cookie AWSELB="C131AB030264D68DBE15F427DA461A7E33CFDF297DC3BEB900D573603CEEF7DE73856C9B69089105D7B6E098CF1C3A20BD41D331636BC242CFD827A445620EA39FE9D26A9E" for domain dashboard-backend.paripassu.com.br, path /, expire 0
* Enable cookie sending with jar of 14 cookies
* Hostname 127.0.0.1 was found in DNS cache
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 7801 (#8)
> POST / HTTP/1.1
> Host: 127.0.0.1:7801
> User-Agent: insomnia/5.7.4
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Length: 1242
> Content-Type: multipart/form-data; boundary=------------------------15a7d9860ebe8cdd
| (1242 B hidden)
* Curl_http_done: called premature == 0
* Empty reply from server
* Connection #8 to host 127.0.0.1 left intact
```

Postman output
```
Could not get any response
There was an error connecting to http://127.0.0.1:7801.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Client certificates are required for this server:
Fix this by adding client certificates in Settings > Certificates
Request timeout:
Change request timeout in Settings > General
```

Java exception:
![image](https://user-images.githubusercontent.com/8113764/29130311-d452aafa-7cff-11e7-8ddd-ff0c6c997858.png)

Export server output during this tests:
```
cmd.exe /c "highcharts-export-server --enableServer 1 --workers 2 --logLevel 4"
    __  ___       __         __               __                      
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______                
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/                
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )                 
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/                  
        ____//___/                  __     _____                          
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /    
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/     
              /_/                                                         
              
Wed Aug 09 2017 12:02:28 GMT-0300 (Hora oficial do Brasil) [verbose] attaching exit listeners to the process..
Wed Aug 09 2017 12:02:28 GMT-0300 (Hora oficial do Brasil) [verbose] Pool started: 
    maxWorkers: 2 
    initialWorkers: 2 
    workLimit: 60 
    listening to process exit: true
Wed Aug 09 2017 12:02:28 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - spawning worker
Wed Aug 09 2017 12:02:28 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 2 - spawning worker
Wed Aug 09 2017 12:02:28 GMT-0300 (Hora oficial do Brasil) [notice] http server started on port 7801
Wed Aug 09 2017 12:02:36 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 95c5437259a040c2b1c2fae9cbd410a7
Wed Aug 09 2017 12:02:36 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:02:36 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:02:36 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:02:36 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:02:36 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 2 - starting work
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 56652876bd2f42e79989f7e4734326b7
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [error] work 95c5437259a040c2b1c2fae9cbd410a7 could not be completed, sending: error when performing chart generation: please check your input data
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 3 - spawning worker
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 1 - starting work
Wed Aug 09 2017 12:02:45 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 2 - process was closed
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 2637f4d97a8a49aab36e7c18e324e665
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [error] work 56652876bd2f42e79989f7e4734326b7 could not be completed, sending: error when performing chart generation: please check your input data
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 4 - spawning worker
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 3 - starting work
Wed Aug 09 2017 12:03:14 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 1 - process was closed
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 81a4dc0b463b4bd497dad29db3a38ca4
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 5 - spawning worker
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 4 - starting work
Wed Aug 09 2017 12:04:11 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 3 - process was closed
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 158035c9bd214afa85d0b8cec3d90b0e
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 6 - spawning worker
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 5 - starting work
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 4 - process was closed
Wed Aug 09 2017 12:04:18 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 5 finished work 158035c9bd214afa85d0b8cec3d90b0e in 259 ms
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 573de000c9994fa2900b0c989a1960ea
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 5 - starting work
Wed Aug 09 2017 12:04:24 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 5 finished work 573de000c9994fa2900b0c989a1960ea in 102 ms
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 50f0f40f3bc242bc984783ee02bd0755
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 5 - starting work
Wed Aug 09 2017 12:04:28 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 5 finished work 50f0f40f3bc242bc984783ee02bd0755 in 118 ms
Wed Aug 09 2017 12:04:33 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request b9f970b411fb4db1bc72e72a73e050fe
Wed Aug 09 2017 12:04:33 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:04:33 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:04:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:04:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:04:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 5 - starting work
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 8d01dd9e363c45e9b917c167314cd807
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 7 - spawning worker
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 6 - starting work
Wed Aug 09 2017 12:06:33 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 5 - process was closed
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 21fb645accab4964a07da3aed4390dab
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 8 - spawning worker
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 7 - starting work
Wed Aug 09 2017 12:09:21 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 6 - process was closed
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request e049ac60a7944833a2e1ba0c7d29d0f3
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 9 - spawning worker
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 8 - starting work
Wed Aug 09 2017 12:09:42 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 7 - process was closed
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 3bcb371332d14be59b7b02759e96232b
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 10 - spawning worker
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 9 - starting work
Wed Aug 09 2017 12:14:16 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 8 - process was closed
Wed Aug 09 2017 12:14:17 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 9 finished work 3bcb371332d14be59b7b02759e96232b in 260 ms
Wed Aug 09 2017 12:14:35 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request e30eb7c58840411b8e9c51419744b9de
Wed Aug 09 2017 12:14:35 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:14:35 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:14:35 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:14:35 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:14:35 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 10 - starting work
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] got incoming HTTP request 9bdef73533504389ad84c63a21594b0a
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] starting export
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] attempting to export from raw input
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - received work, finding available worker
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [notice] the client closed the connection before the chart was done processing
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [notice] restarting worker. working = false
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 11 - spawning worker
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] phantom - found available worker
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [verbose] phantom 9 - starting work
Wed Aug 09 2017 12:35:25 GMT-0300 (Hora oficial do Brasil) [notice] phantom worker 10 - process was closed
Wed Aug 09 2017 12:37:25 GMT-0300 (Hora oficial do Brasil) [error] socket error: { Error: Parse Error
    at Error (native)
    at Socket.socketOnEnd (_http_server.js:425:22)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) bytesParsed: 0, code: 'HPE_INVALID_EOF_STATE' }
Error: request aborted
    at IncomingMessage.onAborted (C:\Users\yuric.PARIPASSU\AppData\Roaming\npm\node_modules\highcharts-export-server\node_modules\raw-body\index.js:269:10)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:283:11)
    at Socket.serverSocketCloseListener (_http_server.js:296:5)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:498:12)
```

**Comment by ypconstante** [comment]
I tested the Export Server using the command line with avg and it worked as expected. Later I'll try the node.js api the check if it works.

**Comment by ypconstante** [comment]
Using the node API also exported the SVG successfully, for some reason this error only happens when running the server. Any idea of what I can do to try to discover why it is happening?

**Comment by cvasseng** [comment]
Could you try pulling from master, and see if the issue is still there? It may be related to this  0c65e278b1af6c323b67c1aee8b4694452191392 fix.

**Comment by cvasseng** [comment]
Given the silence, I'm assuming this is no longer an issue. If it is, feel free to reopen this.
